version: '3.1'

services:

  db:
    container_name: postgres-spring
    image: postgres
    environment:
      POSTGRES_USER: pochu
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
